#my name is Naman
version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: my-lambda-function-name  # Replace with your Lambda function name
        Alias: my-lambda-alias  # Replace with an actual alias
